apitest/urls.py
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('web.urls'), name='web')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/web/urls.py
from django.urls import path
from apps.web import views

app_name= 'web'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.Login.as_view(), name='login')
]

apps/admin/models.py
from django.db import models

# Create your models here.

apps/admin/views.py
from django.shortcuts import render

# Create your views here.

apps/web/views.py
from django.shortcuts import render
from django.http.response import JsonResponse
from django.contrib.auth.decorators import login_required
from django.views import View
from django.conf import settings
import json


# Create your views here.
class Login(View):
    def get(self, request):
        return render(request, 'web/login.html')

    def post(self, request):
        data = request.body
        data = json.loads(data, encoding='utf8')
        username = data.get('username', '')
        password = data.get('password', '')
        print(username, password)
        return JsonResponse({'success': 'success'}, safe=False)


@login_required(login_url=settings.WEB_LOGIN_URL)
def index(request):
    return render(request, 'web/index.html')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}| 测试平台</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta content="一个完整的自动化测试管理平台" name="description"/>
    <meta content="singdl" name="author"/>
    <meta content="新蝶在线,自动化平台,测试管理,关键字驱动，分布式执行" name="keywords"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>

    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}"/>

    <!-- javectormap -->
    <link href="{% static 'admin/libs/jqvmap/jqvmap.min.css' %}" rel="stylesheet" type="text/css"/>
    <!--calendar css-->
    <link href="{% static 'admin/libs/fullcalendar/fullcalendar.min.css' %}" rel="stylesheet" type="text/css"/>

    <!-- Icons css -->
    <link href="{% static 'admin/libs/@mdi/font/css/materialdesignicons.min.css' %}" rel="stylesheet"
          type="text/css"/>
    <link href="{% static 'admin/libs/dripicons/webfont/webfont.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'admin/libs/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'admin/libs/simple-line-icons/css/simple-line-icons.css' %}" rel="stylesheet"
          type="text/css"/>
    <link href="{% static 'admin/libs/metismenu/dist/metisMenu.css' %}" rel="stylesheet" type="text/css"/>

    <!-- element--ui -->
    <!-- 引入样式 -->
    <link href="{% static 'admin/libs/element-ui/lib/theme-chalk/index.css' %}" rel="stylesheet"
          type="text/css">

    <!-- App css -->
    <link href="{% static 'admin/libs/jquery-toast-plugin/jquery.toast.min.css' %}" rel="stylesheet" type="text/css"/>
    <!-- build:css -->
    <link href="{% static 'admin/css/app.css' %}" rel="stylesheet" type="text/css"/>
    <style>
        [v-cloak] {
            display: none;
        }
    </style>
    {% block css %}{% endblock %}
    <!-- endbuild -->
</head>
<body>
{% block header %}
{% include 'header.html' %}
{% endblock %}
{% block content %}{% endblock %}
{% block footer %}
{% include 'footer.html' %}
{% endblock %}
</body>
<!-- 引入vue框架 -->
{#<script src="{% static 'admin/libs/vue/dist/vue.min.js' %}"></script>#}
<script src="{% static 'admin/libs/vue/dist/vue.js' %}"></script>
<script src="{% static 'admin/libs/axios/dist/axios.js' %}"></script>

<!-- 引入element组件库 -->
<script src="{% static 'admin/libs/element-ui/lib/index.js' %}"></script>

<!-- jQuery  -->
<script src="{% static 'admin/libs/jquery/jquery.min.js' %}"></script>
<script src="{% static 'admin/libs/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'admin/libs/jquery-slimscroll/jquery.slimscroll.min.js' %}"></script>
<script src="{% static 'admin/libs/metismenu/dist/metisMenu.js' %}"></script>

<!-- KNOB JS -->
<script src="{% static 'admin/libs/jquery-knob/jquery.knob.min.js' %}"></script>

<script src="{% static 'admin/libs/chart.js/Chart.bundle.min.js' %}"></script>


<script src="{% static 'admin/libs/jqvmap/jquery.vmap.min.js' %}"></script>
<script src="{% static 'admin/libs/jqvmap/maps/jquery.vmap.usa.js' %}"></script>


<!-- Dashboard Init JS -->
<script src="{% static 'admin/libs/tinymce/tinymce.min.js' %}"></script>
<script src="{% static 'admin/libs/jquery-toast-plugin/jquery.toast.min.js' %}"></script>
<script src="{% static 'admin/js/jquery.toastr.js' %}"></script>

<!-- App js -->
<script src="{% static 'admin/js/jquery.core.js' %}"></script>
<script src="{% static 'admin/js/jquery.app.js' %}"></script>


<!--  IE需要es6-promise -->
<script src="{% static 'admin/libs/aliyunvodtools/aliyun-upload-sdk/lib/es6-promise.min.js' %}"></script>
<script src="{% static 'admin/libs/aliyunvodtools/aliyun-upload-sdk/lib/aliyun-oss-sdk-5.3.1.min.js' %}"></script>
<script src="{% static 'admin/libs/aliyunvodtools/aliyun-upload-sdk/aliyun-upload-sdk-1.5.0.min.js' %}"></script>
<script>

    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

</script>

{% block javascript %}{% endblock %}
</html>

templates/web/index.html
{% extends 'base.html' %}
{% block title %}首页{% endblock %}
{% block content %}{% endblock %}

templates/web/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}用户登录{% endblock %}
{% block css %}{% endblock %}

{% block content %}

    <!-- Login -->
    <section>
        <div class="container">
            <div class="row">
                <div class="col-12">

                    <div class="wrapper-page">
                        <div class="account-pages">
                            <div class="account-box">

                                <!-- Logo box-->
                                <div class="account-logo-box">
                                    <h2 class="text-uppercase text-center">
                                        <a href="{% url 'web:index' %}" class="text-success">
                                            <span><img src="{% static 'admin/images/logo_dark.png' %}" alt=""
                                                       height="40"></span>
                                        </a>
                                    </h2>
                                </div>

                                <div class="account-content">
                                    <form>
                                        {{ crsf_token }}
                                        <div class="form-group mb-3">
                                            <label for="username" class="font-weight-medium">账号</label>
                                            <input class="form-control" type="text" id="username" required=""
                                                   placeholder="用户名/手机号/邮箱">
                                        </div>

                                        <div class="form-group mb-3">
                                            <label for="password" class="font-weight-medium">密码</label>
                                            <input class="form-control" type="password" required="" id="password"
                                                   placeholder="密码">
                                        </div>

                                    </form> <!-- end form -->
                                    <div class="form-group row text-center">
                                        <div class="col-12">
                                            <button class="btn btn-block btn-success waves-effect waves-light btn-rounded"
                                                    onclick="login()">登录
                                            </button>
                                        </div>
                                    </div>

                                </div> <!-- end account-content -->

                            </div> <!-- end account-box -->
                        </div>
                        <!-- end account-page-->
                    </div>
                    <!-- end wrapper-page -->

                </div> <!-- end col -->
            </div> <!-- end row -->
        </div> <!-- end container -->
    </section>
    <!-- END HOME -->



{% endblock %}

{% block javascript %}

    <script>
        function login() {
            username = document.getElementById('username').value;
            {#password = psencrypt(document.getElementById('password').value, "{{ public_key|safe }}");#}
            password = document.getElementById('password').value;
            {#luosimaocaptcha = $("#lc-captcha-response").val();#}
            if (username == "") {
                $.NotificationApp.send("提示信息!", "请您先输入用户名！", 'top-center', '#b56d12', 'warning');
            } else if (password == "") {
                $.NotificationApp.send("提示信息!", "您必须输入密码！", 'top-center', '#b56d12', 'warning');

            } else {
                $.ajax({
                    cache: false,
                    type: "POST",
                    url: "{% url 'web:login' %}",
                    data: JSON.stringify({
                        'username': username,
                        'password': password,
                    }),
                    datatype: 'json',
                    async: true,
                    beforeSend: function (xhr, settings) {
                        xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                    },
                    success: function (data) {
                        if (data.success == 'success') {
                            $.NotificationApp.send("提示信息", "登陆成功，即将跳转到登陆界面！", 'top-center', '#5ba035', 'success');
                            window.location.href = request.GET.next;
                        } else {
                            $.NotificationApp.send("提示信息!", data.message, 'top-center', '#b56d12', 'warning');
                        }
                    }
                });
            }
        }
    </script>
{% endblock %}